import { useState } from 'react';
import { siteConfig as config } from './config';

const Arrow = () => <span aria-hidden="true">&#8599;</span>;
const navItems = [['How It Works', 'process'], ['Creators', 'creators'], ['FAQ', 'faq'], ['Contact', 'contact']];

function Logo() { return <a className="logo" href="#home" aria-label={`${config.agencyName} home`}><span>{config.agencyShortName}</span><b>{config.agencyName}</b></a>; }
function Button({ children, href = config.registrationUrl, secondary = false }) { return <a className={`button ${secondary ? 'button-secondary' : ''}`} href={href}>{children} {!secondary && <Arrow />}</a>; }

function Navbar() {
  const [open, setOpen] = useState(false);
  const go = (id) => { setOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); };
  return <header className="navbar"><div className="nav-inner"><Logo /><nav className={`nav-menu ${open ? 'is-open' : ''}`}><a href="#home" onClick={() => setOpen(false)}>Home</a>{navItems.map(([label, id]) => <a href={`#${id}`} key={id} onClick={() => setOpen(false)}>{label}</a>)}<Button>Join Now</Button></nav><button className={`menu-toggle ${open ? 'is-open' : ''}`} onClick={() => setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open}><i></i><i></i><i></i></button></div></header>;
}

function Hero() { return <section className="hero section" id="home"><div className="hero-copy reveal"><p className="eyebrow"><span className="eyebrow-dot"></span> Poppo Live Agency</p><h1>Welcome to Agent <em>Fraol</em> personal page.</h1><p className="hero-lede">It's been 5 months since I started working on Poppo Live. I'm earning over 100,000 birr per month.</p><div className="hero-actions"><Button>Become a Host</Button><a className="text-link" href="#process">Contact ME <Arrow /></a></div><div className="hero-proof"><span className="proof-avatars"><b>+</b><b>+</b><b>+</b></span><span><strong>Creator-first support</strong><small>For your next chapter</small></span></div></div><div className="hero-visual reveal"><div className="visual-ring"></div><div className="hero-image image-a"><img src={config.heroImages[0].src} alt={config.heroImages[0].alt} /></div><div className="hero-image image-b"><img src={config.heroImages[1].src} alt={config.heroImages[1].alt} /></div><div className="hero-image image-c"><img src={config.heroImages[2].src} alt={config.heroImages[2].alt} /></div><div className="float-card live-card"><span className="live-dot"></span><div><b>Agent ID</b><small>000000000</small></div></div><div className="float-card support-card"><span className="float-icon">✦</span><div><b>Agent Fraol</b><small>000000000</small></div></div><span className="visual-label">LIVE / CREATE / GROW</span></div></section>; }

function Process() { return <section className="section process" id="process"><div className="section-heading split-heading"><div><p className="eyebrow">Start here</p><h2>If you want to earn additional income like me</h2></div><p>All you need to do is follow the sequence I will show you. By the way, working on this website does not require any educational qualifications, we can work at our convenient time, we can communicate in our own language, and it gives us the opportunity to meet people from different countries around the world, which makes us enjoy the work.</p></div><div className="steps">{[['01', 'Open Poppo Live', 'Download or open the official platform.'], ['02', 'Create your account', 'Set up your profile and discover your style.'], ['03', 'Apply to our agency', 'Send us a message and complete your application.'], ['04', 'Start streaming', 'Go live, learn as you go, and keep growing.']].map(([num, title, text], index) => <article className="step" key={num}><div className="step-top"><span>{num}</span>{index < 3 && <i></i>}</div><h3>{title}</h3><p>{text}</p></article>)}</div></section>; }

function Creators() { return <section className="section creators" id="creators"><div className="section-heading"><p className="eyebrow">Meet the community</p><h2>Different voices.<br /><em>One shared spark.</em></h2></div><div className="creator-grid">{config.creatorImages.map((creator, index) => <article className="creator-card" key={index}><img src={creator.image} alt={`${creator.name} placeholder profile`} loading="lazy" /><div className="creator-overlay"><span className="tag">{creator.category}</span><h3>{creator.name}</h3><p><span className="live-dot"></span> Live creator</p></div></article>)}</div><p className="placeholder-note">Creator profiles shown are placeholders and will be replaced with approved agency talent.</p></section>; }

function Support() { return <section className="section support"><div className="support-image"><img src={config.heroImages[1].src} alt="Creator preparing for a live stream" loading="lazy" /><div className="support-caption"><span>01</span><strong>You're not doing it alone.</strong></div></div><div className="support-copy"><p className="eyebrow">The human part</p><h2>Support for the moments <em>between</em> the streams.</h2><p>Great live creators are not built by a checklist. Our team is here with the context, feedback, and encouragement that keeps your momentum real.</p><ul>{['Creator onboarding', 'Content and profile guidance', 'Technical help when you need it', 'Community and growth support'].map(item => <li key={item}><span>✓</span>{item}</li>)}</ul></div></section>; }

function FAQ() { const [active, setActive] = useState(0); const items = [['What is Poppo Live?', 'Poppo Live is a live-streaming platform where creators can connect and interact with audiences in real time. Visit the official platform for the latest details.'], ['How do I become a host?', 'Open an account on the official platform, then contact our agency to learn about the current application steps and eligibility.'], ['Do I need experience?', 'No previous streaming experience is required to ask questions or apply. A willingness to learn and show up matters most.'], ['How does the agency support creators?', 'We offer onboarding, practical guidance, technical help, content feedback, and community support.'], ['How can creators earn?', 'Opportunities vary by platform features, eligibility, location, performance, and current rules. We never promise guaranteed income.'], ['Is joining the agency free?', 'Please contact us for the current agency terms and any applicable requirements before joining.'], ['Can I stream using my phone?', 'Live streaming is commonly mobile-first, but check the official platform requirements for your device and region.'], ['How do I contact the agency?', 'Use WhatsApp, Telegram, email, or phone in the contact section below.']]; return <section className="section faq" id="faq"><div className="faq-intro"><p className="eyebrow">Questions, answered</p><h2>Good to know<br /><em>before you go live.</em></h2><p>Still curious? We are happy to talk through the details with you directly.</p><a href={`mailto:${config.email}`} className="text-link">Ask us anything <Arrow /></a></div><div className="faq-list">{items.map(([question, answer], index) => <div className={`faq-item ${active === index ? 'active' : ''}`} key={question}><button onClick={() => setActive(active === index ? -1 : index)}><span>{question}</span><b>{active === index ? '−' : '+'}</b></button><div className="faq-answer"><p>{answer}</p></div></div>)}</div></section>; }

function Contact() { return <section className="section contact" id="contact"><div><p className="eyebrow">Your next move</p><h2>Ready to start your<br /><em>live-streaming journey?</em></h2><p>Join our creator community and take the first step toward becoming a Poppo Live host.</p></div><div className="contact-actions"><Button>Become a Host</Button><a className="button button-secondary" href={`mailto:${config.email}`}>Contact Us <Arrow /></a></div></section>; }

function Footer() { return <footer><div className="footer-top"><div><Logo /><p>A creator-first agency for the next wave of live voices.</p></div><div className="footer-links"><div><small>Explore</small><a href="#process">How It Works</a><a href="#creators">Creators</a></div><div><small>Connect</small><a href={config.whatsappUrl}>WhatsApp</a><a href={config.telegramUrl}>Telegram</a><a href={`mailto:${config.email}`}>Email</a></div></div></div><div className="footer-bottom"><span>© 2026 {config.agencyName}. Placeholder content for client customization.</span><span>Privacy Policy&nbsp;&nbsp; Terms of Service&nbsp;&nbsp; Cookie Policy</span></div></footer>; }

export default function App() { return <><Navbar /><main><Hero /><Process /><Creators />{/* <Earnings /> */}<Support /><FAQ /><Contact /></main><Footer /></>; }